### DISCUSSION TITLE
Disable OS login for Slurm small

### DISCUSSION THREAD

**Discussion by cademirch** [GoogleCloudPlatform/cluster-toolkit#1336] [Q&A] [answered]
Hi there, thank you for this great toolkit. I am very new to Terraform so I am sorry if this is a basic question. 

I've been following the [tutorial](https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/main/docs/tutorials#quickstart-tutorial) to setup the small Slurm cluster and it works well with one hangup. 

It seems that by default the login and controller instances have the metadata entry `enable-oslogin = TRUE` Unfortunately due to my org structure, I cannot use/login to instances with this metadata. 

If I manually change the `enable-oslogin = TRUE` to `enable-oslogin = FALSE` on both instances then I can login and launch slurm jobs. However, it would be great if I could specify this when creating the cluster using Terraform, but I am not sure how. I would appreciate any advice on how to go about this. Thank you!

**Comment by mr0re1** [comment, marked as answer]
He @cademirch  ,
**Slurm GCP V4**  modules used in  `hpc-cluster-small.yaml` example do not expose `enable_oslogin` parameter.
You can try similar example `community/examples/slurm-gcp-v5-hpc-centos7.yaml` that uses **Slurm GCP V5**.
You can set `enable_oslogin` setting on any slurm module you want individually, or set it "for all" by using "global var":
```yaml
 vars:
   project_id:  ## Set GCP Project ID Here ##
   deployment_name: slurm-gcp-v5
   region: us-west4
   zone: us-west4-c
   enable_oslogin: false
```
