### DISCUSSION TITLE
HTCondor tutorial: Creating image error & Artifact Registry?

### DISCUSSION THREAD

**Discussion by jd-foster** [GoogleCloudPlatform/cluster-toolkit#1716] [Q&A] [answered]
Thanks for your previous help.

It appears that in the HTCondor tutorial build script, from here:
`building image using packer module at htcondor-pool/packer/custom-image`
it's trying to create an image in the Container Registry (gcr)?

The issue is this specific error:
```
==> htcondor-pool.googlecompute.toolkit_image: Startup script, if any, has finished running.
==> htcondor-pool.googlecompute.toolkit_image: Deleting instance...
    htcondor-pool.googlecompute.toolkit_image: Instance has been deleted!
==> htcondor-pool.googlecompute.toolkit_image: Creating image...
==> htcondor-pool.googlecompute.toolkit_image: Error waiting for image: googleapi: Error 412: Location asia violates constraint constraints/gcp.resourceLocations on the resource projects/<PROJECT_ID>/global/images/htcondor-10x-20230824t054621z., conditionNotMet
```

(My organisation policy is to restrict projects to resources in the Australian region, so this image creation fails by the `constraints/gcp.resourceLocations` property.)

Is there perhaps a way to use the Artifacts Registry to circumvent this issue, or some other means to get past this?
Thanks again for any help.

**Comment by tpdownes** [comment, marked as answer]
It looks to me like you may have modified the region and zone in the blueprint to match your needs. Could you tell me what those are set to?

The default behavior of Packer is to save the image to a "nearby" region or [multi-region](https://cloud.google.com/storage/docs/locations#location-mr), in this case "asia". Google Cloud VM images are backed by Cloud Storage, so this is the underlying product. I'm a bit surprised it's choosing "asia" if you have an Australian region selected.

You can constrain this behavior by adding this setting to your Packer module:

```yaml
settings:
  ...
  image_storage_locations:
  - australia-southeast1
  - australia-southeast2
```  

if you want it to match the default region for blueprint, you could so something like:

```yaml
settings:
  ...
  image_storage_locations:
  - $(vars.region)
```

**Reply by tpdownes** [reply]
Upstream Packer docs are here:

https://developer.hashicorp.com/packer/plugins/builders/googlecompute

**Reply by jd-foster** [reply]
Thanks Tom.
I assume the place to add this is `community/examples/htc-htcondor.yaml` under
```yaml
- group: packer
  modules:
  - id: custom-image
    source: modules/packer/custom-image
    kind: packer
    use:
    - network1
    - htcondor_install_script
    settings:
```
?
