### DISCUSSION TITLE
Add support to install the PMIX plugin for Slurm

### DISCUSSION THREAD

**Discussion by tomschultz-psivant** [GoogleCloudPlatform/cluster-toolkit#2253] [Ideas and feature requests]
Hello!
 
I'm trying to deploy a cluster with pmix installed as a slurm plugin using the "image-builder" blueprint ( https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/develop/examples/image-builder.yaml ) and I can seem to get the image to build/deploy correctly.

The communication between the controller and login nodes keeps getting messed up, something similar to this https://groups.google.com/g/slurm-users/c/Q7FVkhx-bOsand this https://bugs.schedmd.com/show_bug.cgi?id=10066.
 
I'm guessing that I'm injecting my pmix installation stuff at the wrong moment (https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/develop/examples/image-builder.yaml#L42). Also, it requires re-configuring and installing slurm so I would want to run this at the very end of everything getting setup.

My current guess is that I would actually need to make an Ansible task and follow something similar to how the “install_ompi” tasks are setup through Ansible?

https://github.com/GoogleCloudPlatform/slurm-gcp/blob/849107c9f2e8044051877de579c7308e4e655139/packer/main.pkr.hcl#L31

Is this something that is on the roadmap or possibly something that you all have done before?

**Comment by cdunbar13** [comment]
Hi, just letting you know that we have seen this and are working on it.  

We wanted to know if this is an immediate need or is something that will be needed in the future.

**Reply by tomschultz-psivant** [reply]
Thank you! 

I'm also working on this right now as best as I can.   We are hoping to use this in our production environment by the end of the month and then start transitioning team members over to our cloud cluster.

**Reply by tomschultz-psivant** [reply]
I'm not a slurm expert, but what I believe I'm currently running into is that the controller won't startup properly after I install the pmix plugin through the [startup-script](https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/develop/modules/scripts/startup-script) as described in the [image-builder blueprint](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/3a46dd84d74b89997b6f5f70a3cf314f6d83cd45/examples/image-builder.yaml#L42).

Example:

```
  - id: scripts_for_image
    source: modules/scripts/startup-script
    settings:
      runners:
      - type: shell
        destination: install-pmix.sh
        content: |
          #/bin/bash
          sudo yum install -y wget

          mkdir -p /usr/local/src/pmix
          cd /usr/local/src/pmix

          # Download and install pmix
          wget https://github.com/openpmix/openpmix/releases/download/v4.2.4/pmix-4.2.4.tar.gz
          tar -xzvf pmix-4.2.4.tar.gz
          cd pmix-4.2.4

          # Slurm defaultly looks for pmix in /usr/local/pmix
          mkdir /usr/local/pmix

          ./configure --prefix=/usr/local/pmix |& tee config.out
          make -j 8 |& tee make.out
          make install |& tee install.out

          # Install slurm with pmix support
          cd /usr/local/src/slurm

          ./configure --with-pmix=/usr/local/pmix

          make -j install

          systemctl restart slurmd
```

**Reply by cboneti** [reply]
Hi, let's compare notes. 

I think a better example to  use as a basis would be:  https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/develop/community/examples/hpc-build-slurm-image.yaml as this does the slurm installation on the first place. 

Alas, extra flags are not exposed for slurm at the top level ansible playbook, so something like this is probably needed on slurm-gcp... 

```
diff --git a/ansible/roles/slurm/tasks/install.yml b/ansible/roles/slurm/tasks/install.yml
index eab06b77..602daa96 100644
--- a/ansible/roles/slurm/tasks/install.yml
+++ b/ansible/roles/slurm/tasks/install.yml
@@ -51,6 +51,7 @@
       --prefix={{slurm_paths.install}}
       --sysconfdir={{slurm_paths.etc}}
       --with-jwt={{slurm_paths.install}}
+      --with-pmix=<pmix path>
       --with-systemdsystemunitdir=/usr/lib/systemd/system/
       > /dev/null
     chdir: '{{slurm_paths.build}}'
``` 

I am working on a branch with that and validating it works on the first place...  

Are you using CentOS7 or Rocky as a basis?

**Reply by tomschultz-psivant** [reply]
Ok thanks, I'll look at that example.

We are using CentOS7.

I also went down the slurm-gpc route but I wasn't able to get custom images to build at all through it.  I kept getting permission denied when trying to read the base image from `cloud-hpc-image-public`, which is odd since I'm using those for the hpc-toolkit nodes 🤷‍♂️ .

What I think I'm seeing after installing the plugin via my script above, is that the controller just isn't starting up with the correct parameters to find it's config files and such.   I'm trying to look back through how all that gets built and see if I can find where things diverted.

**Reply by cboneti** [reply]
silly question, in Rocky, `dnf install pmix` works fine. Is it not viable in CentOS7? For the version of slurm you are using (which I guess is 23.02), shouldn't that be sufficient?

**Reply by tomschultz-psivant** [reply]
So when I have `yum install -y pmix` in the startup-script section it doesn't seem to load it completely.

`yum search slurm` doesn't produce and specific pmix plugins. :/

also `yum search pmix`: 
<img width="1030" alt="image" src="https://github.com/GoogleCloudPlatform/hpc-toolkit/assets/87714410/9945cae4-8a67-46c2-8668-44331a442be6">



<img width="1040" alt="image" src="https://github.com/GoogleCloudPlatform/hpc-toolkit/assets/87714410/4a6b2f5d-dded-4667-84ad-489002fff66e">

That didn't seem to work :(

**Reply by cboneti** [reply]
yes, I have verified it is not sufficient to install pmix after slurm, it has to be done before installing slurm and so using the [build slurm image](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/develop/community/examples/hpc-build-slurm-image.yaml) blueprint would be much easier, you could add that on line 52 or so.

**Reply by cboneti** [reply]
I haven't verified this cluster, but in interest of time, the below blueprint should produce an image that you can use for a slurm cluster and that will have pmix setup: 

```
blueprint_name: hpc-build-slurm-image

vars:
  project_id:  ## Set GCP Project ID Here ##
  deployment_name: build-slurm-1
  region: us-central1
  zone: us-central1-a

  image_build_machine_type: n2d-standard-16
  build_from_image_family: hpc-centos-7
  build_from_image_project: cloud-hpc-image-public
  build_from_git_ref: 5.10.4
  built_image_family: my-custom-slurm
  # built_instance_image:
  #   family: $(vars.built_image_family)
  #   project: $(vars.project_id)
  # instance_image_custom: true

deployment_groups:
- group: setup
  modules:
  - id: network
    source: modules/network/vpc

  - id: slurm-build-script
    source: modules/scripts/startup-script
    settings:
      # Do not create Ansible virtual env; Install system wide Ansible below.
      install_ansible: false
      runners:
      - type: shell
        destination: prep-for-slurm-build.sh
        content: |
          #!/bin/bash
          set -e -o pipefail
          # Slurm build on Rocky8 will upgrade to python38 as part of build
          # This is not compatible with ansible-local runner
          yum install -y python3
          yum install -y pmix
          # alternatives --set python3 /usr/bin/python3
          python3 -m pip install pip --upgrade
          python3 -m pip install ansible
          python3 -m pip install selinux
          export PATH=/usr/local/bin:$PATH
          ansible --version
          ansible-galaxy role install googlecloudplatform.google_cloud_ops_agents
      - type: data
        destination: /var/tmp/slurm_vars.json
        content: |
          {
            "reboot": false,
            "install_cuda": false,
            "nvidia_version": "latest",
            "install_ompi": true,
            "install_lustre": false,
            "install_gcsfuse": true
          }
      - type: shell
        destination: install_slurm.sh
        content: |
          #!/bin/bash
          set -e -o pipefail
          ansible-pull \
              -U https://github.com/GoogleCloudPlatform/slurm-gcp -C $(vars.build_from_git_ref) \
              -i localhost, --limit localhost --connection=local \
              -e @/var/tmp/slurm_vars.json \
              ansible/playbook.yml

- group: build-slurm
  modules:
  - id: slurm-custom-image
    source: modules/packer/custom-image
    kind: packer
    settings:
      machine_type: $(vars.image_build_machine_type)
      source_image_family: $(vars.build_from_image_family)
      source_image_project_id: [$(vars.build_from_image_project)]
      image_family: $(vars.built_image_family)
    use:
    - network
    - slurm-build-script
```
