### DISCUSSION TITLE
Sample use of windows-startup-script that returns script to execute

### DISCUSSION THREAD

**Discussion by maucaro** [GoogleCloudPlatform/cluster-toolkit#2534] [General]
The windows-startup-script module's [README](https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/main/community/modules/scripts/windows-startup-script) doesn't describe how to use the output (windows_startup_ps1) to specify startup scripts. Specifically, I am not sure if the list should specify paths to local scripts that will then be included in the image, or if they can be URLs, or if both are supported. A sample would be very helpful.

**Comment by tpdownes** [comment]
Right now the windows-startup-script module is still marked experimental and is focused on the use case of supporting Windows execute points in HTCondor pools. It doesn't have the same level of industrialization as the Linux startup-script solution. In particular, the Linux solution will create the scripts as Cloud Storage objects and download/execute them iteratively. The Windows solution is just a long string to supply in metadata. This example, however, should build the NVIDIA GPU drivers on a Windows VM:

```yaml
blueprint_name: example-win

vars:
  project_id: your-project
  deployment_name: example-win
  region: us-central1
  zone: us-central1-a

deployment_groups:
  - group: primary
    modules:
    - id: network
      source: modules/network/vpc
      settings:
        enable_iap_rdp_ingress: true
        enable_iap_winrm_ingress: true

    - id: win_startup
      source: community/modules/scripts/windows-startup-script
      settings:
        install_nvidia_driver: true

    - id: vm
      source: modules/compute/vm-instance
      use:
      - network
      settings:
        machine_type: n1-standard-16
        guest_accelerator:
        - type: nvidia-tesla-t4
          count: 1
        instance_image:
          family: windows-2016
          project: windows-cloud
        metadata:
          windows-startup-script-ps1: $(join("", win_startup.windows_startup_ps1))
```

I recommend [the Cloud docs](https://cloud.google.com/compute/docs/instances/connecting-to-windows) for further details of connecting to Windows VMs.
