### DISCUSSION TITLE
Slurm GCP v6. VM connectivity issues across zones.

### DISCUSSION THREAD

**Discussion by mr0re1** [GoogleCloudPlatform/cluster-toolkit#3243] [Announcements]
Please be advised of this known issue: https://github.com/GoogleCloudPlatform/cluster-toolkit/issues/3242

If your cluster is affected, please consider a following workaround:

```yaml
# Add `VmDnsSetting` metadata override to all SlurmGCP modules (controller, login, nodeset)
settings:
  metadata:
    VmDnsSetting: GlobalOnly
```

Affected versions:

* [v1.41.0](https://github.com/GoogleCloudPlatform/cluster-toolkit/releases/tag/v1.41.0)
