### DISCUSSION TITLE
Formatting to mount existing DDN exascaler?

### DISCUSSION THREAD

**Discussion by Tristan-Kosciuch** [GoogleCloudPlatform/cluster-toolkit#816] [Q&A] [answered]
I find the documentation unclear on how to use the pre-existing-network-storage module with the DDN exascaler.  @heyealex an example would likely help me. When I deploy my application the wrong lustre IP address is being used and the lustre filesystem is not mounted. This is what I am including in my yaml blueprint:
```
vars:
  lustre_mgs_ip: 10.0.0.218

- group: primary
  modules:
  - id: lustrefs
    source: modules/file-system/pre-existing-network-storage
    settings:
      server_ip: $(vars.lustre_mgs_ip)
      remote_mount: /exacloud
      local_mount: /mnt/exacloud
      fs_type: lustre
```

From the [variables.tf](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/modules/file-system/pre-existing-network-storage/variables.tf) file of the pre-existing-network-storage module I see the format for server_ip should be `<MGS NID>[:<MGS NID>]`. The remote_mount should also be the filesystem name? Any help is appreciated.

I can manually mount the filesystem using the following code so I know the exascaler is working: 
```
#!/bin/bash

LUSTREIP=10.0.0.218 # this is the IP address of the mgs node

cat > /etc/esc-client.cfg << EOF
{
    "Version": "2.0.0",
    "MountConfig": {
        "ClientDevice": "$LUSTREIP@tcp:/exacloud",
        "Mountpoint": "/mnt/exacloud",
        "PackageSource": "http://$LUSTREIP/client-packages"
    }
}
EOF
curl -fsSL http://$LUSTREIP/client-setup-tool -o /usr/sbin/esc-client
chmod +x /usr/sbin/esc-client
esc-client auto setup --config /etc/esc-client.cfg
```

**Comment by heyealex** [comment, marked as answer]
Hello Tristan -
I ran a quick test to determine what is produced by the DDN EXAScaler module, and got the following valid network storage output:
```
network_storage_ddn = {
  "client_install_runner" = # Removed for clarity
  "fs_type" = "lustre"
  "local_mount" = "/scratch"
  "mount_options" = ""
  "mount_runner" = {
    "content" = "mkdir -p /scratch && mount -t lustre 10.0.0.4@tcp:/exacloud /scratch"
    "destination" = "mount-ddn-lustre.sh"
    "type" = "shell"
  }
  "remote_mount" = "/exacloud"
  "server_ip" = "10.0.0.4@tcp"
}
```

I believe it's the `@tcp` after the IP that you are missing in your example. This should definitely be documented better, and I'll make a task for us to do that in the near future. Thanks for bringing this to our attention!

I hope this helps get you unblocked! Let me know if I can clarify anything else or if this does not work for you.

**Reply by Tristan-Kosciuch** [reply]
I still can't get it to mount. I'm building a custom image with packer and I install the lustre modules following [this issue](https://github.com/GoogleCloudPlatform/hpc-toolkit/issues/756). From `sudo journalctl -o cat -u google-startup-scripts` I noticed two different lustre IPs are attempting to be mounted:

- 10.0.0.214 (not sure where this comes from)
- 10.0.0.218 (the proper IP, I created this DDN lustre filesystem a while ago)
The final error message of the ` google-startup-scripts` says 10.0.0.214 failed to me mounted, suggesting the proper IP is not being used. 

Here are the files I use to create my image and slurm cluster

`create-dvmdostem-image.yaml`
```
blueprint_name: create-image

vars:
  project_id:  ## GCP Project ID Here ##
  ssh_username: ## Local username ##
  deployment_name: create-image
  region: us-central1
  zone: us-central1-c
  lustre_mgs_ip: 10.0.0.218@tcp
  startup_timeouts: 300
  network_name: slurm-gcp-v5-net
  subnetwork_name: slurm-gcp-v5-primary-subnet
  first_image_family: dvmdostem-slurm-22-05-6-ubuntu
  second_image_family: dvmdostem-lustre-slurm-22-05-6-ubuntu


deployment_groups:
- group: dvmdostem-image
  modules:
  - id: dvmdostem-image
    source: modules/packer/custom-image
    kind: packer
    settings:
      omit_external_ip: false
      disk_size: 32
      shell_scripts: ["/path/to/install-dependencies.sh"]
      source_image_project_id: [schedmd-slurm-public]
      source_image_family: schedmd-v5-slurm-22-05-6-ubuntu-2004-lts
      image_family: $(vars.first_image_family)
      ssh_username: $(vars.ssh_username)

- group: tmplustre-and-scripts
  modules:
  - id: network0
    source: modules/network/pre-existing-vpc
  - id: tmplustrefs
    source: community/modules/file-system/DDN-EXAScaler
    use: [network0]
    settings:
      local_mount: /mnt/exacloud
      mgs:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mds:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mdt:
        disk_bus: SCSI
        disk_type: pd-ssd
        disk_size: 100
        disk_count: 1
        disk_raid: false
      oss:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      ost:
        disk_bus: SCSI
        disk_type: pd-standard
        disk_size: 500
        disk_count: 1
        disk_raid: false

  - id: mount-at-startup
    source: modules/scripts/startup-script
    settings:
      runners:
      - $(tmplustrefs.install_ddn_lustre_client_runner)
      - type: shell
        destination: "clean_up.sh"
        content: |
          #!/bin/bash
          esc-client unmount -m "/mnt/exacloud"
          rm /etc/esc-client.conf
    outputs: [startup_script]

- group: lustre-image
  modules:
  - id: lustre-image
    source: modules/packer/custom-image
    kind: packer
    settings:
      omit_external_ip: false
      disk_size: 32
      source_image_project_id: [spherical-berm-323321]
      source_image_family: $(vars.first_image_family)
      image_family: $(vars.second_image_family)
      ssh_username: $(vars.ssh_username)
```

After this runs, I create my slurm cluster using this yaml: `slurm.yaml`
```
blueprint_name: slurm-lustre-dvmdostem-v5

vars:
  project_id:  ## GCP project ID ##
  deployment_name: slurm-lustre-dvmdostem-v5
  region: us-central1
  zone: us-central1-c
  lustre_mgs_ip: 10.0.0.218@tcp
  startup_timeouts: 300
  network_name: slurm-gcp-v5-net
  subnetwork_name: slurm-gcp-v5-primary-subnet
  family: dvmdostem-lustre-slurm-22-05-6-ubuntu
  project: spherical-berm-323321
  

deployment_groups:
- group: primary
  modules:
  - id: network1
    source: modules/network/pre-existing-vpc

  - id: lustrefs
    source: modules/file-system/pre-existing-network-storage
    settings:
      server_ip: $(vars.lustre_mgs_ip)
      remote_mount: /exacloud
      local_mount: /mnt/exacloud
      fs_type: lustre

  - id: debug_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 4
      machine_type: n2-highcpu-2
      instance_image:
        family: $(vars.family)
        project: $(vars.project)

  - id: debug_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - lustrefs
    - debug_node_group
    settings:
      partition_name: debug
      enable_placement: false
      is_default: true

  - id: compute_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 20
      machine_type: "n2-highcpu-96"
      instance_image:
        family: $(vars.family)
        project: $(vars.project)
      # set the two following options to true to use spot VMs that are much less expensive but may be stopped at any time
      # preemptible: false
      # enable_spot_vm: false
      # spot_instance_config:
      #   termination_action: "STOP"

  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - lustrefs
    - compute_node_group
    settings:
      partition_name: compute

  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - lustrefs
    - debug_partition
    - compute_partition
    settings:
      machine_type: n2-standard-2
      disk_type: pd-standard
      source_image_family: $(vars.family)
      source_image_project: $(vars.project)
      login_startup_scripts_timeout: $(vars.startup_timeouts)
      controller_startup_scripts_timeout: $(vars.startup_timeouts)
      compute_startup_scripts_timeout: $(vars.startup_timeouts)

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
    use:
    - network1
    - slurm_controller
    settings:
      machine_type: n2-standard-2
      disk_type: pd-standard
      disable_login_public_ips: false
      source_image_family: $(vars.family)
      source_image_project: $(vars.project)

  - id: hpc_dashboard
    source: modules/monitoring/dashboard
    outputs: [instructions]
```

The commands used to create the infra
```
# Create packer image with dvmdostem and DDN lustre dependancies
ghpc create create-dvmdostem-image.yaml --vars project_id=spherical-berm-323321 --vars ssh_username=$USER
cd create-image/dvmdostem-image/dvmdostem-image
packer init .
packer validate .
packer build -parallel-builds=1 .
cd -
terraform -chdir=create-image/tmplustre-and-scripts init
terraform -chdir=create-image/tmplustre-and-scripts validate
terraform -chdir=create-image/tmplustre-and-scripts apply -auto-approve
terraform -chdir=create-image/tmplustre-and-scripts output  -raw startup_script_mount-at-startup > create-image/lustre-image/lustre-image/startup_script.sh
cd create-image/lustre-image/lustre-image
packer init .
packer validate -var startup_script_file=startup_script.sh .
packer build -parallel-builds=1 -var startup_script_file=startup_script.sh .
cd -
terraform -chdir=create-image/tmplustre-and-scripts destroy -auto-approve

# After image is created, spin up slurm cluster
ghpc create slurm.yaml --vars project_id=spherical-berm-323321
terraform -chdir=slurm-lustre-dvmdostem-v5/primary init
terraform -chdir=slurm-lustre-dvmdostem-v5/primary validate
terraform -chdir=slurm-lustre-dvmdostem-v5/primary apply -auto-approve
```

**Reply by Tristan-Kosciuch** [reply]
I'm testing it if works when a new lustre filesystem is created instead of mounting an existing one

Update: doesn't work with a new lustre fs either. Here is a bit more info from `sudo journalctl -o cat -u google-startup-scripts` relating to lustre, errors, and warnings. The `.` indicates skipped logs for brevity. Note the error message at the end showing the wrong IP address (10.0.0.214) is being used to mount lustre.
```
startup-script: Installing Lustre client packages and building DKMS modules ... Installing Lustre client packages and building DKMS modules ... Done.
startup-script: Mounting 10.0.0.214@tcp0:/exacloud at /mnt/exacloud ... Mounting 10.0.0.214@tcp0:/exacloud at /mnt/exacloud ... Done.
startup-script: Thu Jan 12 20:39:16 +0000 2023 Info [1705]: === install_ddn_lustre_client.sh finished with exit_code=0 ===
startup-script: Thu Jan 12 20:39:18 +0000 2023 Info [1705]: === start executing runner: clean_up.sh ===
startup-script: Unmounting /mnt/exacloud ... Unmounting /mnt/exacloud ... Done.
=== clean_up.sh finished with exit_code=0 ===
startup-script: Thu Jan 12 20:39:18 +0000 2023 Info [1705]: === clean_up.sh finished with exit_code=0 ===
startup-script: Packer startup script done.
.
startup-script: WARNING:__main__:config file not found: /slurm/scripts/config.yaml
.
startup-script: ERROR: Error while getting metadata from http://metadata.google.internal/computeMetadata/v1/project/attributes/slurmlustr-slurm-devel
.
startup-script: INFO: Set up network storage
startup-script: INFO: Setting up mount (lustre) 10.0.0.224@tcp:/exacloud to /mnt/exacloud
.
startup-script: INFO: Waiting for '/mnt/exacloud' to be mounted...
startup-script: ERROR: mount of path '/mnt/exacloud' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/mnt/exacloud']' returned non-zero exit status 5.
.
startup-script: INFO: Waiting for '/mnt/exacloud' to be mounted...
startup-script: ERROR: mount of path '/mnt/exacloud' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/mnt/exacloud']' returned non-zero exit status 5.
startup-script: ERROR: CalledProcessError:
startup-script:     command=['mount', '/mnt/exacloud']
startup-script:     returncode=5
startup-script:     stdout:
startup-script:
startup-script:     stderr:
startup-script: mount.lustre: mount 10.0.0.214@tcp0:/exacloud at /mnt/exacloud failed: Input/output error
startup-script: Is the MGS running?
startup-script:
startup-script: ERROR: Aborting setup...
startup-script exit status 0
Finished running startup scripts.
google-startup-scripts.service: Succeeded.
Finished Google Compute Engine Startup Scripts.
```

**Reply by heyealex** [reply]
Hi Tristan,

I'll try to reproduce this on my end. It's weird that the other IP is showing up for you, I'm curious how that made it in. 

I have a couple clarifying questions and requests:
Are you fully using the overwrite flag when you redeploy (`-w/--overwrite`)? 
Can you check the terraform.tfvars file in your deployment directory? It should be at `slurm-lustre-dvmdostem-v5/primary`, I'd like to know if the IP is set correctly there.
Are you able to provide the contents (or part of them) of the /etc/fstab file? That would give me more context on what Slurm on GCP is attempted to do.

I'll provide an update tonight or tomorrow letting you know if I was able to reproduce this failure.

**Reply by Tristan-Kosciuch** [reply]
I `terraform destroy` then clear the directory and recreate it with `ghpc` whenever I make a change to my yaml. Just noticed the overwrite flag, that's less work but not the issue here.

`terraform.tfvars` The correct lustre IP is here. 
```
project          = "spherical-berm-323321"
region           = "us-central1"
lustre_mgs_ip    = "10.0.0.218@tcp"
subnetwork_name  = "slurm-gcp-v5-primary-subnet"
project_id       = "spherical-berm-323321"
startup_timeouts = 300
network_name     = "slurm-gcp-v5-net"
family           = "dvmdostem-lustre-slurm-22-05-6-ubuntu"
zone             = "us-central1-c"
deployment_name  = "slurm-lustre-dvmdostem-v5"
labels = {
  ghpc_blueprint  = "slurm-lustre-dvmdostem-v5"
  ghpc_deployment = "slurm-lustre-dvmdostem-v5"
}
```

`/etc/fstab` Aha..
```
LABEL=cloudimg-rootfs   /        ext4   defaults        0 1
LABEL=UEFI      /boot/efi       vfat    umask=0077      0 1
10.0.0.214@tcp0:/exacloud       /mnt/exacloud   lustre  auto,_netdev,user_xattr 0       0

10.0.0.218@tcp:/exacloud    /mnt/exacloud     lustre      defaults,_netdev  0 0
```

Could deleting /etc/fstab and recreating it correctly as part of my packer build solve the problem?

**Reply by heyealex** [reply]
I ran into the same thing when recreating. I believe the duplicate mount line for /mnt/exacloud was created when you created the image with the DDN network storage attached. 

Deleting the line from /etc/fstab in the image should work, which can be done in a couple of ways:
1. Update the image creation blueprint to include a startup script runner (or additional script) that removes the line.
1. (Short term fix) Create a temporary VM from the image, delete the line, shut down the VM and create a new image in the same family from the VMs disk.

I'll try out (1) and send over an updated blueprint that includes the added runner when I get a chance to test it out. In the meantime, you can try on your end or test this out using (2) to unblock you.

**Reply by heyealex** [reply]
I updated the startup script module in your create image blueprint, just adding one line to remove the existing /mnt/exascaler line:

```yaml
- id: mount-at-startup
    source: modules/scripts/startup-script
    settings:
      runners:
      - $(tmplustrefs.install_ddn_lustre_client_runner)
      - type: shell
        destination: "clean_up.sh"
        content: |
          #!/bin/bash
          esc-client unmount -m "/mnt/exacloud"
          rm /etc/esc-client.conf
          sed -i '/.*\/mnt\/exacloud.*/d' /etc/fstab
    outputs: [startup_script]
```

With an image created using that startup script, I was able to deploy the slurm cluster with DDN EXAscaler mounted (some content removed for brevity):

```
$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute      up   infinite     20  idle~ slurmlustr-compute-ghpc-[0-19]
debug*       up   infinite      4  idle~ slurmlustr-debug-ghpc-[0-3]

$ df
Filesystem                       1K-blocks     Used Available Use% Mounted on
.
10.0.0.10@tcp:/exacloud          517014716     1252 511754200   1% /mnt/exacloud
slurmlustr-controller:/opt/apps   50620416 13930496  36673536  28% /opt/apps
slurmlustr-controller:/home       50620416 13930496  36673536  28% /home
slurmlustr-controller:/etc/munge  50620416 13930496  36673536  28% /etc/munge
.
```

Let me know if that works for you.
