### ISSUE TITLE
suspend_time does it really work

### ISSUE THREAD

**Issue by m4r1k** [GoogleCloudPlatform/cluster-toolkit#164]
Disclaimer: I may be wrong with my noob Slurm understanding.

I was under the impression that the facility `suspend_time` would allow to keep the compute nodes around for some time after the previous job is completed. Instead, the nodes are immediately reclaimed.

```
  # Slurm Controller and Scheduler
  - source: resources/third-party/scheduler/SchedMD-slurm-on-gcp-controller
    kind: terraform
    id: slurm_controller
    use:
    - network1
    - homefs
    - compute_partition
    settings:
      login_node_count: 1
      boot_disk_type: "pd-ssd"
      boot_disk_size: 100
      controller_machine_type: "t2d-standard-2"
      suspend_time: 300
```

See the following logs
```
==> resume.log <==
2022-03-22 12:59:55,261 17116 47376419211584 resume.py INFO: done adding instances: slurm-hpc-slurm-compute-0-[0-1] 6
==> suspend.log <==
2022-03-22 13:00:44,414 17230 46979050408256 suspend.py DEBUG: done deleting instances
2022-03-22 13:00:44,414 17230 46979050408256 suspend.py INFO: done deleting nodes:slurm-hpc-slurm-compute-0-[1,0] job_id:6
```

As you can notice by the timestamp, as soon as the job was over, the nodes got deleted.

```
sacct -l
JobID        JobIDRaw        JobName  Partition  MaxVMSize  MaxVMSizeNode  MaxVMSizeTask  AveVMSize     MaxRSS MaxRSSNode MaxRSSTask     AveRSS MaxPages MaxPagesNode   MaxPagesTask   A
vePages     MinCPU MinCPUNode MinCPUTask     AveCPU   NTasks  AllocCPUS    Elapsed      State ExitCode AveCPUFreq ReqCPUFreqMin ReqCPUFreqMax ReqCPUFreqGov     ReqMem ConsumedEnergy  M
axDiskRead MaxDiskReadNode MaxDiskReadTask    AveDiskRead MaxDiskWrite MaxDiskWriteNode MaxDiskWriteTask   AveDiskWrite    ReqTRES  AllocTRES TRESUsageInAve TRESUsageInMax TRESUsageInM
axNode TRESUsageInMaxTask TRESUsageInMin TRESUsageInMinNode TRESUsageInMinTask TRESUsageInTot TRESUsageOutMax TRESUsageOutMaxNode TRESUsageOutMaxTask TRESUsageOutAve TRESUsageOutTot 
------------ ------------ ---------- ---------- ---------- -------------- -------------- ---------- ---------- ---------- ---------- ---------- -------- ------------ -------------- ---
------- ---------- ---------- ---------- ---------- -------- ---------- ---------- ---------- -------- ---------- ------------- ------------- ------------- ---------- -------------- --
---------- --------------- --------------- -------------- ------------ ---------------- ---------------- -------------- ---------- ---------- -------------- -------------- ------------
------ ------------------ -------------- ------------------ ------------------ -------------- --------------- ------------------- ------------------- --------------- --------------- 
6            6              hostname    compute    221388K slurm-hpc-slu+              0    221388K      1496K slurm-hpc+          1      1494K        0 slurm-hpc-s+              0    
      0   00:00:00 slurm-hpc+          0   00:00:00        2        112   00:00:01  COMPLETED      0:0      2.47M       Unknown       Unknown       Unknown      7936M              0   
         0 slurm-hpc-slur+               0              0            0 slurm-hpc-slurm+                0              0 billing=2+ billing=1+ cpu=00:00:00,+ cpu=00:00:00,+ cpu=slurm-hp
c-slu+ cpu=0,fs/disk=0,m+ cpu=00:00:00,+ cpu=slurm-hpc-slu+ cpu=0,fs/disk=0,m+ cpu=00:00:00,+ energy=0,fs/di+ energy=slurm-hpc-s+           fs/disk=0 energy=0,fs/di+ energy=0,fs/di+ 
```

Is this the expected behavior?
