### ISSUE TITLE
trying to troubleshoot/debug the resume.py script, how do I get it to print more information?

### ISSUE THREAD

**Issue by srcc-chekh** [GoogleCloudPlatform/cluster-toolkit#3337]
### Describe the bug

node creation / power up silently fails sometimes on an otherwise working cloud cluster that scales up and down

### Steps to reproduce

not sure how reproducible it is outside my env

### Expected behavior

when jobs are in the queue, the slurm controller runs the resume script to create more compute nodes

### Actual behavior

After a certain number of running instances is reached, new instances are not created.
I walked through the process with GCP support and we confirmed that we are not hitting any quota limit and we are not seeing any API errors.  It kind of seems like resume.py is silently failing to issue the API call to GCP.

### Version (`gcluster --version`)
v6 with ubuntu 20.04 deployed a while back (months?)

### Blueprint

One basic example blueprint with one filestore and one compute partition with 5000 x e2-highmem-16 nodes.

### Output and logs

slurmctld has stuff like this:
[2024-12-03T00:00:10.013] POWER: power_save: waking nodes hpcmarjola-computenodeset-[1048-1050]
and then stuff like this:
[2024-12-03T00:40:15.017] node hpcmarjola-computenodeset-1048 not resumed by ResumeTimeout(2400) - marking down and power_save

### Additional context

I'm trying to get more detailed information from inside of the resume.py script.  It would be nice to be able to easily run it in debug mode.  In my case, resume.log remains empty and slurmctld.log has the power events because I turned on DebugFlags=Power

For example if you run the script directly you get: "2024-12-03 19:20:00,820 WARNING: SLURM_RESUME_FILE was not in environment. Cannot get detailed job, node, partition allocation data." 
If I catch the SLURM_RESUME_FILE contents (e.g. 
for i in `ps auxf|grep -i resume |grep resume.py |awk '{print $2}' `; do echo $i; cat /proc/$i/environ; done | awk -F= '{print $NF}' |xargs cat  
and pass that through with e.g. 
SLURM_RESUME_FILE=/tmp/test_env python3 /slurm/scripts/resume.py -d -t hpcmarjola-computenodeset-165
I get AttributeError: 'list' object has no attribute 'get'

I would like to get to the point where I can manually run the resume.py script on the cluster side and see the API call results in the GCP logging console (which shows the API calls when things are functioning).

**Comment by srcc-chekh** [comment]
the blueprint name was blueprint_name: hpc-slurm
it was the most basic example, which looked something like this:
```
vars:
  project_id: calico-shared-cluster-aba
  deployment_name: hpc-aba
  region: us-west1
  zone: us-west1-a

  instance_image:
    family: slurm-gcp-6-4-ubuntu-2004-lts
    project: schedmd-slurm-public

# Documentation for each of the modules used below can be found at
# https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/modules/README.md

deployment_groups:
- group: primary
  modules:
  # Source is an embedded module, denoted by "modules/*" without ./, ../, /
  # as a prefix. To refer to a local module, prefix with ./, ../ or /
  # Example - ./modules/network/vpc
  - id: network
    source: modules/network/vpc

  - id: homefs
    source: modules/file-system/filestore
    use: [network]
    settings:
      local_mount: /home
      size_gb: 10996
      filestore_tier: ZONAL

  - id: compute_nodeset
    source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
    use: [network]
    settings:
      node_count_dynamic_max: 500
      machine_type: e2-highmem-16
      on_host_maintenance: MIGRATE

  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v6-partition
    use:
    - compute_nodeset
    settings:
      partition_name: compute
      is_default: true

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v6-login
    use: [network]
    settings:
      name_prefix: login
      machine_type: e2-highmem-4
      disable_login_public_ips: false
      on_host_maintenance: MIGRATE

  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v6-controller
    use:
    - network
    - compute_partition
    - homefs
    - slurm_login
    settings:
      disable_controller_public_ips: false
```

in a fully working basic SLURM cluster, what's the best way to print all the debug info from the resume.py script?
