### ISSUE TITLE
Slurm controller overwrites existing bucket's IAM policies

### ISSUE THREAD

**Issue by siddharthab** [GoogleCloudPlatform/cluster-toolkit#3755]
### Describe the bug

In Slurm controller, when using an existing bucket (`create_bucket = false`), the existing bucket's IAM policy bindings are overwritten through resources `google_storage_bucket_iam_binding.viewers` and `google_storage_bucket_iam_binding.legacy_readers`.

### Steps to reproduce

1. Set up a Slurm cluster with the following controller settings:
```
      - id: slurm_controller
        source: community/modules/scheduler/schedmd-slurm-gcp-v6-controller
        use:
          ...
        settings:
          ...
          create_bucket: false
          bucket_name: ${vars.bucket_name}
          bucket_dir: gcloud/clusters/slurm
```

### Expected behavior

I would expect the existing bucket's IAM policies to be left untouched, or for the new principals to be added to the existing policies, perhaps through the use of a `google_storage_bucket_iam_member` (instead of `google_storage_bucket_iam_binding`) resource.

### Actual behavior

Terraform configuration overwrites the existing policies to remove all other principals through its use of resources `google_storage_bucket_iam_binding.viewers` and `google_storage_bucket_iam_binding.legacy_readers`.

### Version (`gcluster --version`)

gcluster version v1.46.1
Built from 'main' branch.
Commit info: v1.46.1-0-gc491a4ab2
Terraform version: 1.7.4

### Blueprint

If applicable, attach or paste the blueprint YAML used to produce the bug.

```yaml
---
blueprint_name: slurm

vars:
  deployment_name: slurm
  project_id: moonwalkbio
  region: us-central1
  zone: us-central1-c
  compute_node_machine_type: c2-standard-30
  compute_node_max_num: 30
  service_account_email: default@moonwalkbio.iam.gserviceaccount.com

deployment_groups:
  - group: cellranger

    terraform_backend:
      type: gcs
      configuration:
        bucket: moonwalkbio-terraform
        prefix: state/gcp/projects/moonwalkbio/slurm/cellranger

    modules:
      - id: network
        source: modules/network/pre-existing-vpc
        settings:
          project_id: $(vars.project_id)
          region: $(vars.region)
          network_name: default
          subnetwork_name: default

      - id: workdir
        # We don't have access to parallelstore and is likely not needed.
        # If needed, replace below filestore with commented out parallelstore.
        #source: modules/file-system/parallelstore
        #settings:
        #  local_mount: /shared
        #  mount_options: disable-wb-cache,thread-count=20,eq-count=8
        #  private_vpc_connection_peering: servicenetworking.googleapis.com
        source: modules/file-system/filestore
        use: [network]
        settings:
          size_gb: 10240
          filestore_tier: BASIC_HDD
          local_mount: /shared
          # https://cloud.google.com/filestore/docs/mounting-fileshares
          mount_options: hard,timeo=600,retrans=3,rsize=1048576,wsize=1048576,resvport,async,rw

      - id: bucket
        source: modules/file-system/pre-existing-network-storage
        settings:
          remote_mount: moonwalkbio
          local_mount: /gcs/moonwalkbio
          fs_type: gcsfuse
          mount_options: ro,allow_other,implicit_dirs

      - id: compute_nodeset
        source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
        use: [network, bucket]
        settings:
          node_count_dynamic_max: $(vars.compute_node_max_num)
          machine_type: $(vars.compute_node_machine_type)
          bandwidth_tier: gvnic_enabled
          allow_automatic_updates: false
          service_account_email: $(vars.service_account_email)

      - id: compute_partition
        source: community/modules/compute/schedmd-slurm-gcp-v6-partition
        use:
          - compute_nodeset
        settings:
          partition_name: compute
          exclusive: false # allows nodes to stay up after jobs are done
          is_default: true

      - id: slurm_login
        source: community/modules/scheduler/schedmd-slurm-gcp-v6-login
        use: [network]
        settings:
          name_prefix: login
          machine_type: n2-standard-4
          enable_login_public_ips: false
          service_account_email: $(vars.service_account_email)

      - id: slurm_controller
        source: community/modules/scheduler/schedmd-slurm-gcp-v6-controller
        use:
          - network
          - bucket
          - workdir
          - compute_partition
          - slurm_login
        settings:
          enable_controller_public_ips: false
          service_account_email: $(vars.service_account_email)
          create_bucket: false
          bucket_name: moonwalkbio
          bucket_dir: gcloud/clusters/slurm/cellranger
```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `gcluster expand your-blueprint.yaml`.

```yaml
blueprint_name: slurm
ghpc_version: v1.46.1-0-gc491a4ab2
vars:
  compute_node_machine_type: c2-standard-30
  compute_node_max_num: 30
  deployment_name: slurm
  labels:
    ghpc_blueprint: slurm
    ghpc_deployment: ((var.deployment_name))
  project_id: moonwalkbio
  region: us-central1
  service_account_email: default@moonwalkbio.iam.gserviceaccount.com
  zone: us-central1-c
deployment_groups:
  - group: cellranger
    terraform_backend:
      type: gcs
      configuration:
        bucket: moonwalkbio-terraform
        prefix: state/gcp/projects/moonwalkbio/slurm/cellranger
    terraform_providers:
      google:
        source: hashicorp/google
        version: ~> 6.16.0
        configuration:
          project: ((var.project_id))
          region: ((var.region))
          zone: ((var.zone))
      google-beta:
        source: hashicorp/google-beta
        version: ~> 6.16.0
        configuration:
          project: ((var.project_id))
          region: ((var.region))
          zone: ((var.zone))
    modules:
      - source: modules/network/pre-existing-vpc
        kind: terraform
        id: network
        settings:
          network_name: default
          project_id: ((var.project_id))
          region: ((var.region))
          subnetwork_name: default
      - source: modules/file-system/filestore
        kind: terraform
        id: workdir
        use:
          - network
        settings:
          deployment_name: ((var.deployment_name))
          filestore_tier: BASIC_HDD
          labels: ((var.labels))
          local_mount: /shared
          mount_options: hard,timeo=600,retrans=3,rsize=1048576,wsize=1048576,resvport,async,rw
          network_id: ((module.network.network_id))
          project_id: ((var.project_id))
          region: ((var.region))
          size_gb: 10240
          zone: ((var.zone))
      - source: modules/file-system/pre-existing-network-storage
        kind: terraform
        id: bucket
        settings:
          fs_type: gcsfuse
          local_mount: /gcs/moonwalkbio
          mount_options: ro,allow_other,implicit_dirs
          remote_mount: moonwalkbio
      - source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
        kind: terraform
        id: compute_nodeset
        use:
          - network
          - bucket
        settings:
          allow_automatic_updates: false
          bandwidth_tier: gvnic_enabled
          labels: ((var.labels))
          machine_type: ((var.compute_node_machine_type))
          name: compute_nodeset
          network_storage: ((flatten([module.bucket.network_storage])))
          node_count_dynamic_max: ((var.compute_node_max_num))
          project_id: ((var.project_id))
          region: ((var.region))
          service_account_email: ((var.service_account_email))
          subnetwork_self_link: ((module.network.subnetwork_self_link))
          zone: ((var.zone))
      - source: community/modules/compute/schedmd-slurm-gcp-v6-partition
        kind: terraform
        id: compute_partition
        use:
          - compute_nodeset
        settings:
          exclusive: false
          is_default: true
          nodeset: ((flatten([module.compute_nodeset.nodeset])))
          partition_name: compute
      - source: community/modules/scheduler/schedmd-slurm-gcp-v6-login
        kind: terraform
        id: slurm_login
        use:
          - network
        settings:
          enable_login_public_ips: false
          labels: ((var.labels))
          machine_type: n2-standard-4
          name_prefix: login
          project_id: ((var.project_id))
          region: ((var.region))
          service_account_email: ((var.service_account_email))
          subnetwork_self_link: ((module.network.subnetwork_self_link))
          zone: ((var.zone))
      - source: community/modules/scheduler/schedmd-slurm-gcp-v6-controller
        kind: terraform
        id: slurm_controller
        use:
          - network
          - bucket
          - workdir
          - compute_partition
          - slurm_login
        settings:
          bucket_dir: gcloud/clusters/slurm/cellranger
          bucket_name: moonwalkbio
          create_bucket: false
          deployment_name: ((var.deployment_name))
          enable_controller_public_ips: false
          labels: ((var.labels))
          login_nodes: ((flatten([module.slurm_login.login_nodes])))
          network_storage: ((flatten([module.workdir.network_storage, flatten([module.bucket.network_storage])])))
          nodeset: ((flatten([module.compute_partition.nodeset])))
          nodeset_dyn: ((flatten([module.compute_partition.nodeset_dyn])))
          nodeset_tpu: ((flatten([module.compute_partition.nodeset_tpu])))
          partitions: ((flatten([module.compute_partition.partitions])))
          project_id: ((var.project_id))
          region: ((var.region))
          service_account_email: ((var.service_account_email))
          subnetwork_self_link: ((module.network.subnetwork_self_link))
          zone: ((var.zone))
```

### Output and logs

N/A

### Screenshots

N/A

### Execution environment

- OS: macOS
- Shell: zsh
- go version: go version go1.23.5 darwin/arm64

### Additional context

N/A
