### ISSUE TITLE
Startup script doesn't save my files during image creation

### ISSUE THREAD

**Issue by dogukanteber** [GoogleCloudPlatform/cluster-toolkit#3768]
I am trying to create a Slurm cluster using a custom image. I want to install all my dependencies to my image so that I save time from boot time. I've followed the documentation and successfully deployed my cluster, but I can't see my data files and scripts in my VMs. Here is my configuration:

```yaml
blueprint_name: slurm

vars:
  project_id: <project_id>
  deployment_name: slurm
  region: us-central1
  zone: us-central1-c
  network_name: slurm-gcp-net
  subnetwork_name: slurm-gcp-primary-subnet
  custom_image:
    family: rangelands-hpc-base
    project: $(vars.project_id)
  disk_size: 100
  
terraform_backend_defaults:
  type: gcs
  configuration:
    bucket: rangelands-hpc

deployment_groups:
- group: primary
  modules:
  - id: network1
    source: modules/network/pre-existing-vpc
    settings:
        project_id: $(vars.project_id)
        region: $(vars.region)
        network_name: $(vars.network_name)
        subnetwork_name: $(vars.subnetwork_name)

  - id: scripts_for_image
    source: modules/scripts/startup-script
    settings:
      runners:
      - type: data
        source: /tmp/requirements.txt
        destination: /tmp/req.txt
      - type: shell
        destination: "setup_conda_env.sh"
        content: |
          #!/bin/sh
          echo "Hello, world!" > /home/startup_script.txt

- group: packer
  modules:
  - id: custom-image
    source: modules/packer/custom-image
    kind: packer
    use:
    - network1
    - scripts_for_image
    settings:
      source_image_project_id: [schedmd-slurm-public]
      source_image_family: slurm-gcp-6-8-ubuntu-2004-lts
      image_family: $(vars.custom_image.family)
      disk_size: $(vars.disk_size)
      state_timeout: 15m

- group: cluster
  modules:
  - id: compute_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
    use:
      - network1
    settings:
      node_count_dynamic_max: 100
      machine_type: n2-standard-2
      instance_image: $(vars.custom_image)
      instance_image_custom: true
      preemptible: true
      enable_spot_vm: true
      spot_instance_config:
        termination_action: "STOP"

  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v6-partition
    use:
    - compute_node_group
    settings:
      partition_name: compute

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v6-login
    use:
    - network1
    settings:
      machine_type: n2-standard-2
      instance_image: $(vars.custom_image)
      instance_image_custom: true

      disk_type: pd-standard
      enable_login_public_ips: true

  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v6-controller
    use:
    - network1
    - compute_partition
    - slurm_login
    settings:
      machine_type: c2-standard-4
      instance_image: $(vars.custom_image)
      instance_image_custom: true
      disk_type: pd-ssd

```

I see `startup_script.txt` created in the `/home` folder, but I can't find `setup_conda_env.sh` and `/tmp/req.txt` files in my machine. However, I can see my files in my bucket.

This was just a test to make sure my startup script works. I want to configure a conda environment later on. What am I missing in my configuration?
