### ISSUE TITLE
Generalize extra disk feature

### ISSUE THREAD

**Issue by cg2v** [GoogleCloudPlatform/cluster-toolkit#3936]
We'd like to add an extra disk to our login node, but don't need the size nor want the expense of the local ssd configuration available for our instance type. We'd like to be able to have a simple way to mount (an) extra persistent disk(s) in a similar way to how localssd_mountpoint is used to construct and mount a filesystem out of the local ssds. 
The easiest solution for our current single-additional-disk usecase would be to allow us to override the pattern used by setup-raid.yml to identify the devices used to build the raid. Managing multiple disks (which we do not need at present), would be more complex

**Comment by cdunbar13** [comment]
Hi thank you for opening this issue.  I'm assuming you're referring to a Slurm cluster with the login node?  Would the [`additional_disks`](https://github.com/GoogleCloudPlatform/cluster-toolkit/blob/52546519fff56b4829f38ef912d41a6057c3ddf7/community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf#L94) setting for this help or are you looking for something with additional complexity?

**Comment by cg2v** [comment]
i am using additional_disks to attach the storage to the login node instance. this request is about turning the attached disk device into a mounted filesystem. i have worked out appropriate manual steps in ansible and/or shell to do it, but it's similar to the local_ssd_filesystem functionality provided by the startup-script module

**Comment by cdunbar13** [comment]
I think a quick workaround for this would be to use the `var.static_ips` to designate a specific IP within the VPC cidr range, then use that IP in a network_storage block within the nodeset.

Something like

```yaml
- id: slurm_nodeset
  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v6-login
    use: [network]
    settings:
        network_storage:
        - server_ip: 192.168.1.10
           remote_mount: /mnt/test
           local_mount: /mnt/test
           fs_type: nfs
           mount_options: "defaults,_netdev,implicit_dirs"

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v6-login
    use: [network]
    settings:
      static_ips: [192.168.1.10]
      additional_disks:
          ...
```

The formatting might be a bit weird, but I think that would be the gist of it.

If static IPs don't work for your needs, I think a post-deployment solution might be necessary as there would be a dependency loop between the nodeset needing the IP of the login node, and the login node not knowing it until after deployment.
