### ISSUE TITLE
New DWS Flex breaks terraform state

### ISSUE THREAD

**Issue by casassg** [GoogleCloudPlatform/cluster-toolkit#4079]
### Describe the bug

Tricky to reproduce, but:
- Currently DWS Flex when enabled without bulk_insert, sets instance_template `provisioning_model` to `FLEX_START`.
- However when applied, it seems terraform reads it as `STANDARD`. This leads to any new terraform apply to force replace the template even with not changes:

```

~ scheduling {
--
6625 | - availability_domain         = 0 -> null
6626 | - host_error_timeout_seconds  = 0 -> null
6627 | - min_node_cpus               = 0 -> null
6628 | ~ provisioning_model          = "STANDARD" -> "FLEX_START" # forces replacement

```
- This replacement leads to issues with config files as the template is always being replaced on the yaml file:

```

When expanding the plan for
--
4963 | │ module.slurm_cluster.module.slurm_controller.module.slurm_files.google_storage_bucket_object.nodeset_config["a38uf"]
4964 | │ to include new values learned so far during apply, provider
4965 | │ "registry.terraform.io/hashicorp/google" produced an invalid new value for
4966 | │ .md5hash: was known, but now unknown.
```

Short repro of nodeset:

```
  - id: a38_flex_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
    use: [network]
    settings:
      name: a38f
      enable_opportunistic_maintenance: true
      enable_maintenance_reservation: true
      enable_placement: false 
      bandwidth_tier: gvnic_enabled
      machine_type: a3-highgpu-8g
      allow_automatic_updates: false
      disk_type: pd-ssd
      disk_size_gb: 50
      advanced_machine_features:
        threads_per_core: 2 
      on_host_maintenance: TERMINATE
      dws_flex: 
        enabled: true
        use_job_duration: true
        max_run_duration: 604800
      node_count_dynamic_max: 10
```
### Steps to reproduce

1. Use above example nodeset in slurm setup
2. Apply once (no issues)
3. terraform apply  again

### Expected behavior

Terraform apply works without issues

### Actual behavior

```

│ When expanding the plan for
--
4963 | │ module.slurm_cluster.module.slurm_controller.module.slurm_files.google_storage_bucket_object.nodeset_config["a38uf"]
4964 | │ to include new values learned so far during apply, provider
4965 | │ "registry.terraform.io/hashicorp/google" produced an invalid new value for
4966 | │ .md5hash: was known, but now unknown.

```

### Version (`gcluster --version`)

`v0.50`

### Blueprint

See above, full blueprint omitted as its too long and not needed to repro issue.

### Additional context

It seems to work fine when using bulk_insert: true
