### ISSUE TITLE
preemtible machines

### ISSUE THREAD

**Issue by AlexeySaff** [GoogleCloudPlatform/cluster-toolkit#4269]
when we set nodeset with 
      preemptible: true

machine is created with new feature spotVM without specifying "limit runtime" options. 

My question: can we return back to old preempt or specify "limit runtime" for spotVM?

https://cloud.google.com/compute/docs/instances/preemptible

**Comment by abbas1902** [comment]
Hi @AlexeySaff , thank you for opening this bug. You can use the following instance properties in order to "limit runtime" specifically via the `maxRunDuration` metadata:

```
  - id: spot_nodeset
    source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
    use: [network]
    settings:
      ... rest of settings ...
      enable_spot_vm: true
      instance_properties:
        scheduling:
          maxRunDuration: { seconds: $(2 * 60 * 60) } # 2 hours
          onHostMaintenance: TERMINATE
          instanceTerminationAction: DELETE
```

Hopefully this helps achieves your desired behavior.
