### ISSUE TITLE
Provider produced inconsistent final plan when updating a cluster nodesets

### ISSUE THREAD

**Issue by 4doom4** [GoogleCloudPlatform/cluster-toolkit#4272]
### Describe the bug

Generating the cluster with my blueprint is not an issue but if I run after deploying the deployment command again:

./gcluster deploy ../prod

I always get the same errors when working on the nodesets. I haven't seen this before and it was working until recently. The same behaviour is experienced when I make small changes to the blueprint and run the deployment after regenerating the input:

./gcluster create ../production.yml -l ERROR -o ../ -w --force

### Steps to reproduce

1. Generate a new blueprint with at least one nodeset
2. Deploy it
3. Re-deploy or generate new inputs and re-deploy

### Expected behavior

Update completes without error

### Actual behavior

Deployment always stops at the nodesets

### Version (`gcluster --version`)

gcluster version v1.54.0
Built from 'main' branch.
Commit info: v1.54.0-0-g07fdb16f4
Terraform version: 1.8.5

### Blueprint

Can be provided if needed

### Output and logs

```text
When expanding the plan for
module.slurm_controller.module.slurm_files.google_storage_bucket_object.nodeset_config["gpuv100spotnod"]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/google" produced an invalid new value for
.generation: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.slurm_controller.module.slurm_files.google_storage_bucket_object.nodeset_config["gpuv100spotnod"]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/google" produced an invalid new value for
.md5hash: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.slurm_controller.module.slurm_files.google_storage_bucket_object.nodeset_config["gpuv100spotnod"]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/google" produced an invalid new value for
.crc32c: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

### Execution environment

- OS: macOS
- Shell (To find this, run `ps -p $$`): zsh
- go version: go1.23.2 darwin/arm64

**Comment by 4doom4** [comment]
I investigated further and found that the issue is somewhere with the enable_spot_vm: true block. the following block works:

```
  - id: n1t4_n
    source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
    use:
    - network
    settings:
      instance_image: $(vars.slurm_image)
      startup_script: $(startup_tools.startup_script)
      node_count_dynamic_max: 32
      machine_type: n1-standard-8
      guest_accelerator:
        - type: nvidia-tesla-t4
          count: 1
      enable_placement: false # the default is: true
  
  - id: n1t4_p
    source: community/modules/compute/schedmd-slurm-gcp-v6-partition
    use:
    - n1t4_n
    settings:
      partition_name: gput4
      exclusive: false # allows nodes to stay up after jobs are done
```

but this block fails with the above message when deploying the second time:

```
  - id: n1t4_sn
    source: community/modules/compute/schedmd-slurm-gcp-v6-nodeset
    use:
    - network
    settings:
      instance_image: $(vars.slurm_image)
      startup_script: $(startup_tools.startup_script)
      node_count_dynamic_max: 16
      machine_type: n1-standard-8
      guest_accelerator:
        - type: nvidia-tesla-t4
          count: 1
      enable_placement: false # the default is: true
      enable_spot_vm: true

  - id: n1t4_sp
    source: community/modules/compute/schedmd-slurm-gcp-v6-partition
    use:
    - n1t4_sn
    settings:
      partition_name: spot4gput4
      exclusive: false # allows nodes to stay up after jobs are done
```

maybe this helps
